2023-09-18 00:14:32.199 | ERROR    | __main__:<module>:22 - 'charmap' codec can't encode characters in position 0-6: character maps to <undefined>
Traceback (most recent call last):

> File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 20, in <module>
    launching_the_program_with_account_verification()
    └ <function launching_the_program_with_account_verification at 0x0000021CD6FB4AF0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 15, in launching_the_program_with_account_verification
    main_menu()  # Основное меню программы
    └ <function main_menu at 0x0000021CD6FB4670>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\menu\main_menu_interface.py", line 26, in main_menu
    clearing_console_showing_banner()  # Чистим консоль, выводим банер
    └ <function clearing_console_showing_banner at 0x0000021CD6F86A70>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\auxiliary_functions\auxiliary_functions.py", line 56, in clearing_console_showing_banner
    banner()  # Ставим банер программы, для красивого визуального отображения
    └ <function banner at 0x0000021CD6EF6830>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\menu\app_banner.py", line 9, in banner
    console.print("╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗", style="bold red", justify="center")
    │       └ <function Console.print at 0x0000021CD6EF44C0>
    └ <console width=79 None>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1646, in print
    with self:
         └ <console width=79 None>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 848, in __exit__
    self._exit_buffer()
    │    └ <function Console._exit_buffer at 0x0000021CD6EDEA70>
    └ <console width=79 None>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 806, in _exit_buffer
    self._check_buffer()
    │    └ <function Console._check_buffer at 0x0000021CD6EF48B0>
    └ <console width=79 None>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1999, in _check_buffer
    legacy_windows_render(
    └ <function legacy_windows_render at 0x0000021CD6FB4DC0>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
    │    │            │     └ Style(color=Color('red', ColorType.STANDARD, number=1), bold=True)
    │    │            └ '╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗'
    │    └ <function LegacyWindowsTerm.write_styled at 0x0000021CD6EF5F30>
    └ <rich._win32_console.LegacyWindowsTerm object at 0x0000021CD6F8A650>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
    │    │          └ '╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗'
    │    └ <function LegacyWindowsTerm.write_text at 0x0000021CD6EF5EA0>
    └ <rich._win32_console.LegacyWindowsTerm object at 0x0000021CD6F8A650>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
    │    │     └ '╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗'
    │    └ <built-in method write of _io.TextIOWrapper object at 0x0000021CD27D1150>
    └ <rich._win32_console.LegacyWindowsTerm object at 0x0000021CD6F8A650>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           │      │              │     │    │      └ <EncodingMap object at 0x0000021CD2239E80>
           │      │              │     │    └ 'strict'
           │      │              │     └ <encodings.cp1251.IncrementalEncoder object at 0x0000021CD2888820>
           │      │              └ '╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗'
           │      └ <built-in function charmap_encode>
           └ <module 'codecs' from 'C:\\Users\\zhvit\\AppData\\Local\\Programs\\Python\\Python310\\lib\\codecs.py'>

UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-6: character maps to <undefined>
2023-09-18 00:18:08.053 | ERROR    | __main__:<module>:22 - 'charmap' codec can't encode characters in position 0-6: character maps to <undefined>
Traceback (most recent call last):

> File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 20, in <module>
    launching_the_program_with_account_verification()
    └ <function launching_the_program_with_account_verification at 0x000001EC7A8B8A60>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 15, in launching_the_program_with_account_verification
    main_menu()  # Основное меню программы
    └ <function main_menu at 0x000001EC7A8B85E0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\menu\main_menu_interface.py", line 26, in main_menu
    clearing_console_showing_banner()  # Чистим консоль, выводим банер
    └ <function clearing_console_showing_banner at 0x000001EC7A88A9E0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\auxiliary_functions\auxiliary_functions.py", line 56, in clearing_console_showing_banner
    banner()  # Ставим банер программы, для красивого визуального отображения
    └ <function banner at 0x000001EC7A7F27A0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\menu\app_banner.py", line 9, in banner
    console.print("╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗", style="bold red", justify="center")
    │       └ <function Console.print at 0x000001EC7A7F0430>
    └ <console width=79 None>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1646, in print
    with self:
         └ <console width=79 None>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 848, in __exit__
    self._exit_buffer()
    │    └ <function Console._exit_buffer at 0x000001EC7A7DA9E0>
    └ <console width=79 None>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 806, in _exit_buffer
    self._check_buffer()
    │    └ <function Console._check_buffer at 0x000001EC7A7F0820>
    └ <console width=79 None>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1999, in _check_buffer
    legacy_windows_render(
    └ <function legacy_windows_render at 0x000001EC7A8B8D30>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
    │    │            │     └ Style(color=Color('red', ColorType.STANDARD, number=1), bold=True)
    │    │            └ '╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗'
    │    └ <function LegacyWindowsTerm.write_styled at 0x000001EC7A7F1EA0>
    └ <rich._win32_console.LegacyWindowsTerm object at 0x000001EC7A8968F0>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
    │    │          └ '╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗'
    │    └ <function LegacyWindowsTerm.write_text at 0x000001EC7A7F1E10>
    └ <rich._win32_console.LegacyWindowsTerm object at 0x000001EC7A8968F0>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
    │    │     └ '╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗'
    │    └ <built-in method write of _io.TextIOWrapper object at 0x000001EC760D1150>
    └ <rich._win32_console.LegacyWindowsTerm object at 0x000001EC7A8968F0>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           │      │              │     │    │      └ <EncodingMap object at 0x000001EC75BFBAD0>
           │      │              │     │    └ 'strict'
           │      │              │     └ <encodings.cp1251.IncrementalEncoder object at 0x000001EC76188820>
           │      │              └ '╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗'
           │      └ <built-in function charmap_encode>
           └ <module 'codecs' from 'C:\\Users\\zhvit\\AppData\\Local\\Programs\\Python\\Python310\\lib\\codecs.py'>

UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-6: character maps to <undefined>
2023-09-18 00:18:08.053 | ERROR    | __main__:<module>:22 - 'charmap' codec can't encode characters in position 0-6: character maps to <undefined>
Traceback (most recent call last):

> File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 20, in <module>
    launching_the_program_with_account_verification()
    └ <function launching_the_program_with_account_verification at 0x000001EC7A8B8A60>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 15, in launching_the_program_with_account_verification
    main_menu()  # Основное меню программы
    └ <function main_menu at 0x000001EC7A8B85E0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\menu\main_menu_interface.py", line 26, in main_menu
    clearing_console_showing_banner()  # Чистим консоль, выводим банер
    └ <function clearing_console_showing_banner at 0x000001EC7A88A9E0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\auxiliary_functions\auxiliary_functions.py", line 56, in clearing_console_showing_banner
    banner()  # Ставим банер программы, для красивого визуального отображения
    └ <function banner at 0x000001EC7A7F27A0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\menu\app_banner.py", line 9, in banner
    console.print("╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗", style="bold red", justify="center")
    │       └ <function Console.print at 0x000001EC7A7F0430>
    └ <console width=79 None>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1646, in print
    with self:
         └ <console width=79 None>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 848, in __exit__
    self._exit_buffer()
    │    └ <function Console._exit_buffer at 0x000001EC7A7DA9E0>
    └ <console width=79 None>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 806, in _exit_buffer
    self._check_buffer()
    │    └ <function Console._check_buffer at 0x000001EC7A7F0820>
    └ <console width=79 None>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\console.py", line 1999, in _check_buffer
    legacy_windows_render(
    └ <function legacy_windows_render at 0x000001EC7A8B8D30>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_windows_renderer.py", line 17, in legacy_windows_render
    term.write_styled(text, style)
    │    │            │     └ Style(color=Color('red', ColorType.STANDARD, number=1), bold=True)
    │    │            └ '╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗'
    │    └ <function LegacyWindowsTerm.write_styled at 0x000001EC7A7F1EA0>
    └ <rich._win32_console.LegacyWindowsTerm object at 0x000001EC7A8968F0>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_win32_console.py", line 442, in write_styled
    self.write_text(text)
    │    │          └ '╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗'
    │    └ <function LegacyWindowsTerm.write_text at 0x000001EC7A7F1E10>
    └ <rich._win32_console.LegacyWindowsTerm object at 0x000001EC7A8968F0>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\site-packages\rich\_win32_console.py", line 403, in write_text
    self.write(text)
    │    │     └ '╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗'
    │    └ <built-in method write of _io.TextIOWrapper object at 0x000001EC760D1150>
    └ <rich._win32_console.LegacyWindowsTerm object at 0x000001EC7A8968F0>

  File "C:\Users\zhvit\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           │      │              │     │    │      └ <EncodingMap object at 0x000001EC75BFBAD0>
           │      │              │     │    └ 'strict'
           │      │              │     └ <encodings.cp1251.IncrementalEncoder object at 0x000001EC76188820>
           │      │              └ '╔╦╗╔═╗╦  ╔═╗╔═╗╦═╗╔═╗╔╦╗    ╔═╗╔╦╗╔╦╗    ╔╗ ╔═╗╔╦╗'
           │      └ <built-in function charmap_encode>
           └ <module 'codecs' from 'C:\\Users\\zhvit\\AppData\\Local\\Programs\\Python\\Python310\\lib\\codecs.py'>

UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-6: character maps to <undefined>
2023-11-01 16:51:38.702 | ERROR    | __main__:<module>:20 - DatabaseHandler.cleaning_db() missing 1 required positional argument: 'self'
Traceback (most recent call last):

> File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 18, in <module>
    launching_the_program_with_account_verification()
    └ <function launching_the_program_with_account_verification at 0x000001C34B06E0C0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 12, in launching_the_program_with_account_verification
    deleting_files_by_dictionary()
    └ <function deleting_files_by_dictionary at 0x000001C34B062AC0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\telegram_actions\account_verification.py", line 24, in deleting_files_by_dictionary
    writing_names_found_files_to_the_db()  # Сканируем папку с аккаунтами на наличие сессий
    └ <function writing_names_found_files_to_the_db at 0x000001C34AFE7740>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\telegram_actions\telegram_actions.py", line 59, in writing_names_found_files_to_the_db
    db_handler.cleaning_db(name_database_table="config")  # Чистим базу данных с аккаунтами
    │          └ <function DatabaseHandler.cleaning_db at 0x000001C34994FC40>
    └ <class 'system.sqlite_working_tools.sqlite_working_tools.DatabaseHandler'>

TypeError: DatabaseHandler.cleaning_db() missing 1 required positional argument: 'self'
2023-11-01 16:51:38.702 | ERROR    | __main__:<module>:20 - DatabaseHandler.cleaning_db() missing 1 required positional argument: 'self'
Traceback (most recent call last):

> File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 18, in <module>
    launching_the_program_with_account_verification()
    └ <function launching_the_program_with_account_verification at 0x000001C34B06E0C0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 12, in launching_the_program_with_account_verification
    deleting_files_by_dictionary()
    └ <function deleting_files_by_dictionary at 0x000001C34B062AC0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\telegram_actions\account_verification.py", line 24, in deleting_files_by_dictionary
    writing_names_found_files_to_the_db()  # Сканируем папку с аккаунтами на наличие сессий
    └ <function writing_names_found_files_to_the_db at 0x000001C34AFE7740>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\telegram_actions\telegram_actions.py", line 59, in writing_names_found_files_to_the_db
    db_handler.cleaning_db(name_database_table="config")  # Чистим базу данных с аккаунтами
    │          └ <function DatabaseHandler.cleaning_db at 0x000001C34994FC40>
    └ <class 'system.sqlite_working_tools.sqlite_working_tools.DatabaseHandler'>

TypeError: DatabaseHandler.cleaning_db() missing 1 required positional argument: 'self'
2023-11-01 16:52:19.406 | ERROR    | __main__:<module>:20 - DatabaseHandler.cleaning_db() missing 1 required positional argument: 'self'
Traceback (most recent call last):

> File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 18, in <module>
    launching_the_program_with_account_verification()
    └ <function launching_the_program_with_account_verification at 0x0000022E8E792520>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 12, in launching_the_program_with_account_verification
    deleting_files_by_dictionary()
    └ <function deleting_files_by_dictionary at 0x0000022E8E77EE80>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\telegram_actions\account_verification.py", line 24, in deleting_files_by_dictionary
    writing_names_found_files_to_the_db()  # Сканируем папку с аккаунтами на наличие сессий
    └ <function writing_names_found_files_to_the_db at 0x0000022E8E6FB6A0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\telegram_actions\telegram_actions.py", line 59, in writing_names_found_files_to_the_db
    db_handler.cleaning_db(name_database_table="config")  # Чистим базу данных с аккаунтами
    │          └ <function DatabaseHandler.cleaning_db at 0x0000022E8D06FBA0>
    └ <class 'system.sqlite_working_tools.sqlite_working_tools.DatabaseHandler'>

TypeError: DatabaseHandler.cleaning_db() missing 1 required positional argument: 'self'
2023-11-01 16:52:19.406 | ERROR    | __main__:<module>:20 - DatabaseHandler.cleaning_db() missing 1 required positional argument: 'self'
Traceback (most recent call last):

> File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 18, in <module>
    launching_the_program_with_account_verification()
    └ <function launching_the_program_with_account_verification at 0x0000022E8E792520>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 12, in launching_the_program_with_account_verification
    deleting_files_by_dictionary()
    └ <function deleting_files_by_dictionary at 0x0000022E8E77EE80>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\telegram_actions\account_verification.py", line 24, in deleting_files_by_dictionary
    writing_names_found_files_to_the_db()  # Сканируем папку с аккаунтами на наличие сессий
    └ <function writing_names_found_files_to_the_db at 0x0000022E8E6FB6A0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\telegram_actions\telegram_actions.py", line 59, in writing_names_found_files_to_the_db
    db_handler.cleaning_db(name_database_table="config")  # Чистим базу данных с аккаунтами
    │          └ <function DatabaseHandler.cleaning_db at 0x0000022E8D06FBA0>
    └ <class 'system.sqlite_working_tools.sqlite_working_tools.DatabaseHandler'>

TypeError: DatabaseHandler.cleaning_db() missing 1 required positional argument: 'self'
2023-11-01 16:59:20.751 | ERROR    | __main__:<module>:20 - incomplete input
Traceback (most recent call last):

> File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 18, in <module>
    launching_the_program_with_account_verification()
    └ <function launching_the_program_with_account_verification at 0x000001C694F92520>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 12, in launching_the_program_with_account_verification
    deleting_files_by_dictionary()
    └ <function deleting_files_by_dictionary at 0x000001C694F7EE80>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\telegram_actions\account_verification.py", line 24, in deleting_files_by_dictionary
    writing_names_found_files_to_the_db()  # Сканируем папку с аккаунтами на наличие сессий
    └ <function writing_names_found_files_to_the_db at 0x000001C694EFB6A0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\telegram_actions\telegram_actions.py", line 63, in writing_names_found_files_to_the_db
    db_handler.write_data_to_db(creating_a_table, writing_data_to_a_table, entities)
    │          │                │                 │                        └ ['7655060', 'cc1290cd733c1f1d407598e5a31be4a8', '79112613851']
    │          │                │                 └ 'INSERT INTO config (id, hash, phone) VALUES (?, ?, ?'
    │          │                └ 'CREATE TABLE IF NOT EXISTS config(id, hash, phone)'
    │          └ <function DatabaseHandler.write_data_to_db at 0x000001C69387F6A0>
    └ <system.sqlite_working_tools.sqlite_working_tools.DatabaseHandler object at 0x000001C694F05290>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\sqlite_working_tools\sqlite_working_tools.py", line 55, in write_data_to_db
    self.cursor.executemany(writing_data_to_a_table, (entities,))
    │    │      │           │                         └ ['7655060', 'cc1290cd733c1f1d407598e5a31be4a8', '79112613851']
    │    │      │           └ 'INSERT INTO config (id, hash, phone) VALUES (?, ?, ?'
    │    │      └ <method 'executemany' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000001C694FA18C0>
    └ <system.sqlite_working_tools.sqlite_working_tools.DatabaseHandler object at 0x000001C694F05290>

sqlite3.OperationalError: incomplete input
2023-11-01 16:59:20.751 | ERROR    | __main__:<module>:20 - incomplete input
Traceback (most recent call last):

> File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 18, in <module>
    launching_the_program_with_account_verification()
    └ <function launching_the_program_with_account_verification at 0x000001C694F92520>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\main.py", line 12, in launching_the_program_with_account_verification
    deleting_files_by_dictionary()
    └ <function deleting_files_by_dictionary at 0x000001C694F7EE80>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\telegram_actions\account_verification.py", line 24, in deleting_files_by_dictionary
    writing_names_found_files_to_the_db()  # Сканируем папку с аккаунтами на наличие сессий
    └ <function writing_names_found_files_to_the_db at 0x000001C694EFB6A0>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\telegram_actions\telegram_actions.py", line 63, in writing_names_found_files_to_the_db
    db_handler.write_data_to_db(creating_a_table, writing_data_to_a_table, entities)
    │          │                │                 │                        └ ['7655060', 'cc1290cd733c1f1d407598e5a31be4a8', '79112613851']
    │          │                │                 └ 'INSERT INTO config (id, hash, phone) VALUES (?, ?, ?'
    │          │                └ 'CREATE TABLE IF NOT EXISTS config(id, hash, phone)'
    │          └ <function DatabaseHandler.write_data_to_db at 0x000001C69387F6A0>
    └ <system.sqlite_working_tools.sqlite_working_tools.DatabaseHandler object at 0x000001C694F05290>

  File "C:\Users\zhvit\YandexDisk\Python\telegram_bot_smm\system\sqlite_working_tools\sqlite_working_tools.py", line 55, in write_data_to_db
    self.cursor.executemany(writing_data_to_a_table, (entities,))
    │    │      │           │                         └ ['7655060', 'cc1290cd733c1f1d407598e5a31be4a8', '79112613851']
    │    │      │           └ 'INSERT INTO config (id, hash, phone) VALUES (?, ?, ?'
    │    │      └ <method 'executemany' of 'sqlite3.Cursor' objects>
    │    └ <sqlite3.Cursor object at 0x000001C694FA18C0>
    └ <system.sqlite_working_tools.sqlite_working_tools.DatabaseHandler object at 0x000001C694F05290>

sqlite3.OperationalError: incomplete input
